# Generated by Django 5.0.4 on 2024-04-22 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkino', '0003_remove_modelkino_podpiska_modelkino_podpiska'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='modelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=1000)),
                ('podpiska', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='appkino.modelpodpiska')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
