# Generated by Django 5.0.4 on 2024-04-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkino', '0004_modelprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelkino',
            name='otziv',
        ),
        migrations.AddField(
            model_name='modelotziv',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appkino.modelkino', verbose_name='Кино'),
        ),
    ]
